spring:
  main:
    web-environment: false

  datasource:
    url: jdbc:h2:mem:cim;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 

#  datasource:
#    url: jdbc:mysql://localhost:3306/cim?useSSL=false
#    username: root
#    password: 
#    dbcp2:
#      test-while-idle: true
#      validation-query: SELECT 1

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

flyway:
  locations: classpath:db/migration/{vendor}
