CREATE TABLE graveowner (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	marca BIGINT,
	cnp VARCHAR(32),
	nume VARCHAR(128) NOT NULL,
	prenume VARCHAR(128) NOT NULL,
	adresa VARCHAR(256) NOT NULL,
	cod_loc INT,
	localitate VARCHAR(128),
	judet VARCHAR(64),
	tara VARCHAR(64),
	str VARCHAR(128),
	nr VARCHAR(32),
	bl VARCHAR(32),
	sc VARCHAR(32),
	et VARCHAR(32),
	ap VARCHAR(32),
	cod_post VARCHAR(64),
	tel VARCHAR(64),
	fax VARCHAR(64),
	mail VARCHAR(128),
	nr_contr VARCHAR(64),
	data_contr TIMESTAMP,
	contract VARCHAR(64),
	act VARCHAR(32),
	seria VARCHAR(32),
	nr_act VARCHAR(64),
	emitator VARCHAR(128),
	data_act TIMESTAMP,
	dubiu VARCHAR(64),
	data_dubiu TIMESTAMP,
	avans VARCHAR(64),
	an_debut INT,
	an_final INT,
	modif VARCHAR(64),
	avizat VARCHAR(64),
	data_aviz TIMESTAMP
);

CREATE TABLE graveyard (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	nume VARCHAR(128) NOT NULL,
	localitate VARCHAR(128) NOT NULL,
	judet VARCHAR(64) NOT NULL,
	tara VARCHAR(64) NOT NULL,
	str VARCHAR(128) NOT NULL,
	nr VARCHAR(32) NOT NULL
);

CREATE TABLE exempt (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	cod INT NOT NULL,
	nume VARCHAR(128) NOT NULL
);

CREATE TABLE grave (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	marca BIGINT,
	graveowner_id BIGINT NOT NULL,
	graveyard_id BIGINT NOT NULL,
	exempt_id BIGINT NULL,
	cod_zona INT,
	sector VARCHAR(32),
	rind VARCHAR(32),
	pozitie VARCHAR(32),
	nr_locuri INT,
	ani INT,
	data_incep TIMESTAMP,
	data_exp TIMESTAMP,
	nr_ch VARCHAR(32),
	data_ch TIMESTAMP,
	suma DECIMAL,
	contract VARCHAR(32),
	nr_contr VARCHAR(32),
	data_contr TIMESTAMP,
	ind INT,
	stare VARCHAR(32),
	data_stare TIMESTAMP,
	transe INT,
	cod_cs INT,
	matricola INT,
	modif VARCHAR(32),
	FOREIGN KEY (graveowner_id) REFERENCES graveowner(id),
	FOREIGN KEY (graveyard_id) REFERENCES graveyard(id),
	FOREIGN KEY (exempt_id) REFERENCES exempt(id)
);

CREATE INDEX graveowner_id_idx ON grave(graveowner_id);
CREATE INDEX graveyard_id_idx ON grave(graveyard_id);
CREATE INDEX exempt_id_idx ON grave(exempt_id);
